Delete workspace on build start
Fixes an issue whereby subsequent builds of any branch fail with
obscure messages along the lines of:
> error: wrong index v2 file size in .git/objects/pack/pack-b360de1f7cfbce9b7fa4b4c11ea4dc4daea3d1f7.idx

Depends on https://github.com/alphagov/govuk-jenkinslib/pull/91

Tested in https://github.com/alphagov/rails_translation_manager/pull/22

Trello: https://trello.com/c/Pq7ffzxM/2752-investigate-rails-translation-manager-failing-builds